################################
# API Manager
autodiscoveryId: "20835953"

# Listener
https:
  port: "8082"
  
response-timeout: "30000"
################################

openbeta:
  protocol: "https"
  host: "api.openbeta.io"